name: CI
description: Test

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Check Schema
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Check GraphQL Schema
        uses: kamilkisiela/graphql-inspector@main
        with:
          schema: "main:schema.graphql"
