name: Inspector Flow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: diff
        run: graphql-inspector diff 'master:schema.graphql' 'example/schemas/deep.graphql'
