name: GraphQL Inspector Check

on:
  push:
    branches:
      - main

jobs:
  graphql-inspector:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: yarn install

      - name: Run GraphQL Inspector
        uses: kamilkisiela/graphql-inspector@master
        with:
          schema: schema.graphql
